# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ihsan/SFML_RPG-master/SFML_RPG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ihsan/SFML_RPG-master/SFML_RPG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ihsan/SFML_RPG-master/SFML_RPG/CMakeFiles /home/ihsan/SFML_RPG-master/SFML_RPG//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ihsan/SFML_RPG-master/SFML_RPG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameKelompok

# Build rule for target.
GameKelompok: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameKelompok
.PHONY : GameKelompok

# fast build rule for target.
GameKelompok/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/build
.PHONY : GameKelompok/fast

AIComponent.o: AIComponent.cpp.o
.PHONY : AIComponent.o

# target to build an object file
AIComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIComponent.cpp.o
.PHONY : AIComponent.cpp.o

AIComponent.i: AIComponent.cpp.i
.PHONY : AIComponent.i

# target to preprocess a source file
AIComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIComponent.cpp.i
.PHONY : AIComponent.cpp.i

AIComponent.s: AIComponent.cpp.s
.PHONY : AIComponent.s

# target to generate assembly for a file
AIComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIComponent.cpp.s
.PHONY : AIComponent.cpp.s

AIFollow.o: AIFollow.cpp.o
.PHONY : AIFollow.o

# target to build an object file
AIFollow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIFollow.cpp.o
.PHONY : AIFollow.cpp.o

AIFollow.i: AIFollow.cpp.i
.PHONY : AIFollow.i

# target to preprocess a source file
AIFollow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIFollow.cpp.i
.PHONY : AIFollow.cpp.i

AIFollow.s: AIFollow.cpp.s
.PHONY : AIFollow.s

# target to generate assembly for a file
AIFollow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIFollow.cpp.s
.PHONY : AIFollow.cpp.s

AIOption.o: AIOption.cpp.o
.PHONY : AIOption.o

# target to build an object file
AIOption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIOption.cpp.o
.PHONY : AIOption.cpp.o

AIOption.i: AIOption.cpp.i
.PHONY : AIOption.i

# target to preprocess a source file
AIOption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIOption.cpp.i
.PHONY : AIOption.cpp.i

AIOption.s: AIOption.cpp.s
.PHONY : AIOption.s

# target to generate assembly for a file
AIOption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AIOption.cpp.s
.PHONY : AIOption.cpp.s

AnimationComponent.o: AnimationComponent.cpp.o
.PHONY : AnimationComponent.o

# target to build an object file
AnimationComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AnimationComponent.cpp.o
.PHONY : AnimationComponent.cpp.o

AnimationComponent.i: AnimationComponent.cpp.i
.PHONY : AnimationComponent.i

# target to preprocess a source file
AnimationComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AnimationComponent.cpp.i
.PHONY : AnimationComponent.cpp.i

AnimationComponent.s: AnimationComponent.cpp.s
.PHONY : AnimationComponent.s

# target to generate assembly for a file
AnimationComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AnimationComponent.cpp.s
.PHONY : AnimationComponent.cpp.s

AttributeComponent.o: AttributeComponent.cpp.o
.PHONY : AttributeComponent.o

# target to build an object file
AttributeComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AttributeComponent.cpp.o
.PHONY : AttributeComponent.cpp.o

AttributeComponent.i: AttributeComponent.cpp.i
.PHONY : AttributeComponent.i

# target to preprocess a source file
AttributeComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AttributeComponent.cpp.i
.PHONY : AttributeComponent.cpp.i

AttributeComponent.s: AttributeComponent.cpp.s
.PHONY : AttributeComponent.s

# target to generate assembly for a file
AttributeComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/AttributeComponent.cpp.s
.PHONY : AttributeComponent.cpp.s

Bird1.o: Bird1.cpp.o
.PHONY : Bird1.o

# target to build an object file
Bird1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Bird1.cpp.o
.PHONY : Bird1.cpp.o

Bird1.i: Bird1.cpp.i
.PHONY : Bird1.i

# target to preprocess a source file
Bird1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Bird1.cpp.i
.PHONY : Bird1.cpp.i

Bird1.s: Bird1.cpp.s
.PHONY : Bird1.s

# target to generate assembly for a file
Bird1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Bird1.cpp.s
.PHONY : Bird1.cpp.s

Bow.o: Bow.cpp.o
.PHONY : Bow.o

# target to build an object file
Bow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Bow.cpp.o
.PHONY : Bow.cpp.o

Bow.i: Bow.cpp.i
.PHONY : Bow.i

# target to preprocess a source file
Bow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Bow.cpp.i
.PHONY : Bow.cpp.i

Bow.s: Bow.cpp.s
.PHONY : Bow.s

# target to generate assembly for a file
Bow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Bow.cpp.s
.PHONY : Bow.cpp.s

CharacterTab.o: CharacterTab.cpp.o
.PHONY : CharacterTab.o

# target to build an object file
CharacterTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/CharacterTab.cpp.o
.PHONY : CharacterTab.cpp.o

CharacterTab.i: CharacterTab.cpp.i
.PHONY : CharacterTab.i

# target to preprocess a source file
CharacterTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/CharacterTab.cpp.i
.PHONY : CharacterTab.cpp.i

CharacterTab.s: CharacterTab.cpp.s
.PHONY : CharacterTab.s

# target to generate assembly for a file
CharacterTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/CharacterTab.cpp.s
.PHONY : CharacterTab.cpp.s

DefaultEditorMode.o: DefaultEditorMode.cpp.o
.PHONY : DefaultEditorMode.o

# target to build an object file
DefaultEditorMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/DefaultEditorMode.cpp.o
.PHONY : DefaultEditorMode.cpp.o

DefaultEditorMode.i: DefaultEditorMode.cpp.i
.PHONY : DefaultEditorMode.i

# target to preprocess a source file
DefaultEditorMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/DefaultEditorMode.cpp.i
.PHONY : DefaultEditorMode.cpp.i

DefaultEditorMode.s: DefaultEditorMode.cpp.s
.PHONY : DefaultEditorMode.s

# target to generate assembly for a file
DefaultEditorMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/DefaultEditorMode.cpp.s
.PHONY : DefaultEditorMode.cpp.s

EditorMode.o: EditorMode.cpp.o
.PHONY : EditorMode.o

# target to build an object file
EditorMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EditorMode.cpp.o
.PHONY : EditorMode.cpp.o

EditorMode.i: EditorMode.cpp.i
.PHONY : EditorMode.i

# target to preprocess a source file
EditorMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EditorMode.cpp.i
.PHONY : EditorMode.cpp.i

EditorMode.s: EditorMode.cpp.s
.PHONY : EditorMode.s

# target to generate assembly for a file
EditorMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EditorMode.cpp.s
.PHONY : EditorMode.cpp.s

EditorState.o: EditorState.cpp.o
.PHONY : EditorState.o

# target to build an object file
EditorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EditorState.cpp.o
.PHONY : EditorState.cpp.o

EditorState.i: EditorState.cpp.i
.PHONY : EditorState.i

# target to preprocess a source file
EditorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EditorState.cpp.i
.PHONY : EditorState.cpp.i

EditorState.s: EditorState.cpp.s
.PHONY : EditorState.s

# target to generate assembly for a file
EditorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EditorState.cpp.s
.PHONY : EditorState.cpp.s

Enemy.o: Enemy.cpp.o
.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i
.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s
.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

EnemyEditorMode.o: EnemyEditorMode.cpp.o
.PHONY : EnemyEditorMode.o

# target to build an object file
EnemyEditorMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemyEditorMode.cpp.o
.PHONY : EnemyEditorMode.cpp.o

EnemyEditorMode.i: EnemyEditorMode.cpp.i
.PHONY : EnemyEditorMode.i

# target to preprocess a source file
EnemyEditorMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemyEditorMode.cpp.i
.PHONY : EnemyEditorMode.cpp.i

EnemyEditorMode.s: EnemyEditorMode.cpp.s
.PHONY : EnemyEditorMode.s

# target to generate assembly for a file
EnemyEditorMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemyEditorMode.cpp.s
.PHONY : EnemyEditorMode.cpp.s

EnemySpawnerTile.o: EnemySpawnerTile.cpp.o
.PHONY : EnemySpawnerTile.o

# target to build an object file
EnemySpawnerTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemySpawnerTile.cpp.o
.PHONY : EnemySpawnerTile.cpp.o

EnemySpawnerTile.i: EnemySpawnerTile.cpp.i
.PHONY : EnemySpawnerTile.i

# target to preprocess a source file
EnemySpawnerTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemySpawnerTile.cpp.i
.PHONY : EnemySpawnerTile.cpp.i

EnemySpawnerTile.s: EnemySpawnerTile.cpp.s
.PHONY : EnemySpawnerTile.s

# target to generate assembly for a file
EnemySpawnerTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemySpawnerTile.cpp.s
.PHONY : EnemySpawnerTile.cpp.s

EnemySystem.o: EnemySystem.cpp.o
.PHONY : EnemySystem.o

# target to build an object file
EnemySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemySystem.cpp.o
.PHONY : EnemySystem.cpp.o

EnemySystem.i: EnemySystem.cpp.i
.PHONY : EnemySystem.i

# target to preprocess a source file
EnemySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemySystem.cpp.i
.PHONY : EnemySystem.cpp.i

EnemySystem.s: EnemySystem.cpp.s
.PHONY : EnemySystem.s

# target to generate assembly for a file
EnemySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/EnemySystem.cpp.s
.PHONY : EnemySystem.cpp.s

Entity.o: Entity.cpp.o
.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i
.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s
.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameState.o: GameState.cpp.o
.PHONY : GameState.o

# target to build an object file
GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/GameState.cpp.o
.PHONY : GameState.cpp.o

GameState.i: GameState.cpp.i
.PHONY : GameState.i

# target to preprocess a source file
GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/GameState.cpp.i
.PHONY : GameState.cpp.i

GameState.s: GameState.cpp.s
.PHONY : GameState.s

# target to generate assembly for a file
GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/GameState.cpp.s
.PHONY : GameState.cpp.s

GraphicsSettings.o: GraphicsSettings.cpp.o
.PHONY : GraphicsSettings.o

# target to build an object file
GraphicsSettings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/GraphicsSettings.cpp.o
.PHONY : GraphicsSettings.cpp.o

GraphicsSettings.i: GraphicsSettings.cpp.i
.PHONY : GraphicsSettings.i

# target to preprocess a source file
GraphicsSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/GraphicsSettings.cpp.i
.PHONY : GraphicsSettings.cpp.i

GraphicsSettings.s: GraphicsSettings.cpp.s
.PHONY : GraphicsSettings.s

# target to generate assembly for a file
GraphicsSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/GraphicsSettings.cpp.s
.PHONY : GraphicsSettings.cpp.s

Gui.o: Gui.cpp.o
.PHONY : Gui.o

# target to build an object file
Gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Gui.cpp.o
.PHONY : Gui.cpp.o

Gui.i: Gui.cpp.i
.PHONY : Gui.i

# target to preprocess a source file
Gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Gui.cpp.i
.PHONY : Gui.cpp.i

Gui.s: Gui.cpp.s
.PHONY : Gui.s

# target to generate assembly for a file
Gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Gui.cpp.s
.PHONY : Gui.cpp.s

HitboxComponent.o: HitboxComponent.cpp.o
.PHONY : HitboxComponent.o

# target to build an object file
HitboxComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/HitboxComponent.cpp.o
.PHONY : HitboxComponent.cpp.o

HitboxComponent.i: HitboxComponent.cpp.i
.PHONY : HitboxComponent.i

# target to preprocess a source file
HitboxComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/HitboxComponent.cpp.i
.PHONY : HitboxComponent.cpp.i

HitboxComponent.s: HitboxComponent.cpp.s
.PHONY : HitboxComponent.s

# target to generate assembly for a file
HitboxComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/HitboxComponent.cpp.s
.PHONY : HitboxComponent.cpp.s

Inventory.o: Inventory.cpp.o
.PHONY : Inventory.o

# target to build an object file
Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Inventory.cpp.o
.PHONY : Inventory.cpp.o

Inventory.i: Inventory.cpp.i
.PHONY : Inventory.i

# target to preprocess a source file
Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Inventory.cpp.i
.PHONY : Inventory.cpp.i

Inventory.s: Inventory.cpp.s
.PHONY : Inventory.s

# target to generate assembly for a file
Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Inventory.cpp.s
.PHONY : Inventory.cpp.s

Item.o: Item.cpp.o
.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i
.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s
.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Item.cpp.s
.PHONY : Item.cpp.s

MainMenuState.o: MainMenuState.cpp.o
.PHONY : MainMenuState.o

# target to build an object file
MainMenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MainMenuState.cpp.o
.PHONY : MainMenuState.cpp.o

MainMenuState.i: MainMenuState.cpp.i
.PHONY : MainMenuState.i

# target to preprocess a source file
MainMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MainMenuState.cpp.i
.PHONY : MainMenuState.cpp.i

MainMenuState.s: MainMenuState.cpp.s
.PHONY : MainMenuState.s

# target to generate assembly for a file
MainMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MainMenuState.cpp.s
.PHONY : MainMenuState.cpp.s

MeleeWeapon.o: MeleeWeapon.cpp.o
.PHONY : MeleeWeapon.o

# target to build an object file
MeleeWeapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MeleeWeapon.cpp.o
.PHONY : MeleeWeapon.cpp.o

MeleeWeapon.i: MeleeWeapon.cpp.i
.PHONY : MeleeWeapon.i

# target to preprocess a source file
MeleeWeapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MeleeWeapon.cpp.i
.PHONY : MeleeWeapon.cpp.i

MeleeWeapon.s: MeleeWeapon.cpp.s
.PHONY : MeleeWeapon.s

# target to generate assembly for a file
MeleeWeapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MeleeWeapon.cpp.s
.PHONY : MeleeWeapon.cpp.s

MovementComponent.o: MovementComponent.cpp.o
.PHONY : MovementComponent.o

# target to build an object file
MovementComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MovementComponent.cpp.o
.PHONY : MovementComponent.cpp.o

MovementComponent.i: MovementComponent.cpp.i
.PHONY : MovementComponent.i

# target to preprocess a source file
MovementComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MovementComponent.cpp.i
.PHONY : MovementComponent.cpp.i

MovementComponent.s: MovementComponent.cpp.s
.PHONY : MovementComponent.s

# target to generate assembly for a file
MovementComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/MovementComponent.cpp.s
.PHONY : MovementComponent.cpp.s

PauseMenu.o: PauseMenu.cpp.o
.PHONY : PauseMenu.o

# target to build an object file
PauseMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PauseMenu.cpp.o
.PHONY : PauseMenu.cpp.o

PauseMenu.i: PauseMenu.cpp.i
.PHONY : PauseMenu.i

# target to preprocess a source file
PauseMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PauseMenu.cpp.i
.PHONY : PauseMenu.cpp.i

PauseMenu.s: PauseMenu.cpp.s
.PHONY : PauseMenu.s

# target to generate assembly for a file
PauseMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PauseMenu.cpp.s
.PHONY : PauseMenu.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Player.cpp.s
.PHONY : Player.cpp.s

PlayerGUI.o: PlayerGUI.cpp.o
.PHONY : PlayerGUI.o

# target to build an object file
PlayerGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PlayerGUI.cpp.o
.PHONY : PlayerGUI.cpp.o

PlayerGUI.i: PlayerGUI.cpp.i
.PHONY : PlayerGUI.i

# target to preprocess a source file
PlayerGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PlayerGUI.cpp.i
.PHONY : PlayerGUI.cpp.i

PlayerGUI.s: PlayerGUI.cpp.s
.PHONY : PlayerGUI.s

# target to generate assembly for a file
PlayerGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PlayerGUI.cpp.s
.PHONY : PlayerGUI.cpp.s

PlayerGUITabs.o: PlayerGUITabs.cpp.o
.PHONY : PlayerGUITabs.o

# target to build an object file
PlayerGUITabs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PlayerGUITabs.cpp.o
.PHONY : PlayerGUITabs.cpp.o

PlayerGUITabs.i: PlayerGUITabs.cpp.i
.PHONY : PlayerGUITabs.i

# target to preprocess a source file
PlayerGUITabs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PlayerGUITabs.cpp.i
.PHONY : PlayerGUITabs.cpp.i

PlayerGUITabs.s: PlayerGUITabs.cpp.s
.PHONY : PlayerGUITabs.s

# target to generate assembly for a file
PlayerGUITabs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/PlayerGUITabs.cpp.s
.PHONY : PlayerGUITabs.cpp.s

RangedWeapon.o: RangedWeapon.cpp.o
.PHONY : RangedWeapon.o

# target to build an object file
RangedWeapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/RangedWeapon.cpp.o
.PHONY : RangedWeapon.cpp.o

RangedWeapon.i: RangedWeapon.cpp.i
.PHONY : RangedWeapon.i

# target to preprocess a source file
RangedWeapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/RangedWeapon.cpp.i
.PHONY : RangedWeapon.cpp.i

RangedWeapon.s: RangedWeapon.cpp.s
.PHONY : RangedWeapon.s

# target to generate assembly for a file
RangedWeapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/RangedWeapon.cpp.s
.PHONY : RangedWeapon.cpp.s

Rat.o: Rat.cpp.o
.PHONY : Rat.o

# target to build an object file
Rat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Rat.cpp.o
.PHONY : Rat.cpp.o

Rat.i: Rat.cpp.i
.PHONY : Rat.i

# target to preprocess a source file
Rat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Rat.cpp.i
.PHONY : Rat.cpp.i

Rat.s: Rat.cpp.s
.PHONY : Rat.s

# target to generate assembly for a file
Rat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Rat.cpp.s
.PHONY : Rat.cpp.s

RegularTile.o: RegularTile.cpp.o
.PHONY : RegularTile.o

# target to build an object file
RegularTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/RegularTile.cpp.o
.PHONY : RegularTile.cpp.o

RegularTile.i: RegularTile.cpp.i
.PHONY : RegularTile.i

# target to preprocess a source file
RegularTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/RegularTile.cpp.i
.PHONY : RegularTile.cpp.i

RegularTile.s: RegularTile.cpp.s
.PHONY : RegularTile.s

# target to generate assembly for a file
RegularTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/RegularTile.cpp.s
.PHONY : RegularTile.cpp.s

Scorpion.o: Scorpion.cpp.o
.PHONY : Scorpion.o

# target to build an object file
Scorpion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Scorpion.cpp.o
.PHONY : Scorpion.cpp.o

Scorpion.i: Scorpion.cpp.i
.PHONY : Scorpion.i

# target to preprocess a source file
Scorpion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Scorpion.cpp.i
.PHONY : Scorpion.cpp.i

Scorpion.s: Scorpion.cpp.s
.PHONY : Scorpion.s

# target to generate assembly for a file
Scorpion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Scorpion.cpp.s
.PHONY : Scorpion.cpp.s

SettingsState.o: SettingsState.cpp.o
.PHONY : SettingsState.o

# target to build an object file
SettingsState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/SettingsState.cpp.o
.PHONY : SettingsState.cpp.o

SettingsState.i: SettingsState.cpp.i
.PHONY : SettingsState.i

# target to preprocess a source file
SettingsState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/SettingsState.cpp.i
.PHONY : SettingsState.cpp.i

SettingsState.s: SettingsState.cpp.s
.PHONY : SettingsState.s

# target to generate assembly for a file
SettingsState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/SettingsState.cpp.s
.PHONY : SettingsState.cpp.s

SkillComponent.o: SkillComponent.cpp.o
.PHONY : SkillComponent.o

# target to build an object file
SkillComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/SkillComponent.cpp.o
.PHONY : SkillComponent.cpp.o

SkillComponent.i: SkillComponent.cpp.i
.PHONY : SkillComponent.i

# target to preprocess a source file
SkillComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/SkillComponent.cpp.i
.PHONY : SkillComponent.cpp.i

SkillComponent.s: SkillComponent.cpp.s
.PHONY : SkillComponent.s

# target to generate assembly for a file
SkillComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/SkillComponent.cpp.s
.PHONY : SkillComponent.cpp.s

Spider.o: Spider.cpp.o
.PHONY : Spider.o

# target to build an object file
Spider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Spider.cpp.o
.PHONY : Spider.cpp.o

Spider.i: Spider.cpp.i
.PHONY : Spider.i

# target to preprocess a source file
Spider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Spider.cpp.i
.PHONY : Spider.cpp.i

Spider.s: Spider.cpp.s
.PHONY : Spider.s

# target to generate assembly for a file
Spider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Spider.cpp.s
.PHONY : Spider.cpp.s

State.o: State.cpp.o
.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i
.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s
.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/State.cpp.s
.PHONY : State.cpp.s

Sword.o: Sword.cpp.o
.PHONY : Sword.o

# target to build an object file
Sword.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Sword.cpp.o
.PHONY : Sword.cpp.o

Sword.i: Sword.cpp.i
.PHONY : Sword.i

# target to preprocess a source file
Sword.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Sword.cpp.i
.PHONY : Sword.cpp.i

Sword.s: Sword.cpp.s
.PHONY : Sword.s

# target to generate assembly for a file
Sword.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Sword.cpp.s
.PHONY : Sword.cpp.s

Tab.o: Tab.cpp.o
.PHONY : Tab.o

# target to build an object file
Tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Tab.cpp.o
.PHONY : Tab.cpp.o

Tab.i: Tab.cpp.i
.PHONY : Tab.i

# target to preprocess a source file
Tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Tab.cpp.i
.PHONY : Tab.cpp.i

Tab.s: Tab.cpp.s
.PHONY : Tab.s

# target to generate assembly for a file
Tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Tab.cpp.s
.PHONY : Tab.cpp.s

TextTagSystem.o: TextTagSystem.cpp.o
.PHONY : TextTagSystem.o

# target to build an object file
TextTagSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/TextTagSystem.cpp.o
.PHONY : TextTagSystem.cpp.o

TextTagSystem.i: TextTagSystem.cpp.i
.PHONY : TextTagSystem.i

# target to preprocess a source file
TextTagSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/TextTagSystem.cpp.i
.PHONY : TextTagSystem.cpp.i

TextTagSystem.s: TextTagSystem.cpp.s
.PHONY : TextTagSystem.s

# target to generate assembly for a file
TextTagSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/TextTagSystem.cpp.s
.PHONY : TextTagSystem.cpp.s

Tile.o: Tile.cpp.o
.PHONY : Tile.o

# target to build an object file
Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Tile.cpp.o
.PHONY : Tile.cpp.o

Tile.i: Tile.cpp.i
.PHONY : Tile.i

# target to preprocess a source file
Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Tile.cpp.i
.PHONY : Tile.cpp.i

Tile.s: Tile.cpp.s
.PHONY : Tile.s

# target to generate assembly for a file
Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Tile.cpp.s
.PHONY : Tile.cpp.s

TileMap.o: TileMap.cpp.o
.PHONY : TileMap.o

# target to build an object file
TileMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/TileMap.cpp.o
.PHONY : TileMap.cpp.o

TileMap.i: TileMap.cpp.i
.PHONY : TileMap.i

# target to preprocess a source file
TileMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/TileMap.cpp.i
.PHONY : TileMap.cpp.i

TileMap.s: TileMap.cpp.s
.PHONY : TileMap.s

# target to generate assembly for a file
TileMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/TileMap.cpp.s
.PHONY : TileMap.cpp.s

VectorMath.o: VectorMath.cpp.o
.PHONY : VectorMath.o

# target to build an object file
VectorMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/VectorMath.cpp.o
.PHONY : VectorMath.cpp.o

VectorMath.i: VectorMath.cpp.i
.PHONY : VectorMath.i

# target to preprocess a source file
VectorMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/VectorMath.cpp.i
.PHONY : VectorMath.cpp.i

VectorMath.s: VectorMath.cpp.s
.PHONY : VectorMath.s

# target to generate assembly for a file
VectorMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/VectorMath.cpp.s
.PHONY : VectorMath.cpp.s

Weapon.o: Weapon.cpp.o
.PHONY : Weapon.o

# target to build an object file
Weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Weapon.cpp.o
.PHONY : Weapon.cpp.o

Weapon.i: Weapon.cpp.i
.PHONY : Weapon.i

# target to preprocess a source file
Weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Weapon.cpp.i
.PHONY : Weapon.cpp.i

Weapon.s: Weapon.cpp.s
.PHONY : Weapon.s

# target to generate assembly for a file
Weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/Weapon.cpp.s
.PHONY : Weapon.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/main.cpp.s
.PHONY : main.cpp.s

stdafx.o: stdafx.cpp.o
.PHONY : stdafx.o

# target to build an object file
stdafx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/stdafx.cpp.o
.PHONY : stdafx.cpp.o

stdafx.i: stdafx.cpp.i
.PHONY : stdafx.i

# target to preprocess a source file
stdafx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/stdafx.cpp.i
.PHONY : stdafx.cpp.i

stdafx.s: stdafx.cpp.s
.PHONY : stdafx.s

# target to generate assembly for a file
stdafx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameKelompok.dir/build.make CMakeFiles/GameKelompok.dir/stdafx.cpp.s
.PHONY : stdafx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameKelompok"
	@echo "... AIComponent.o"
	@echo "... AIComponent.i"
	@echo "... AIComponent.s"
	@echo "... AIFollow.o"
	@echo "... AIFollow.i"
	@echo "... AIFollow.s"
	@echo "... AIOption.o"
	@echo "... AIOption.i"
	@echo "... AIOption.s"
	@echo "... AnimationComponent.o"
	@echo "... AnimationComponent.i"
	@echo "... AnimationComponent.s"
	@echo "... AttributeComponent.o"
	@echo "... AttributeComponent.i"
	@echo "... AttributeComponent.s"
	@echo "... Bird1.o"
	@echo "... Bird1.i"
	@echo "... Bird1.s"
	@echo "... Bow.o"
	@echo "... Bow.i"
	@echo "... Bow.s"
	@echo "... CharacterTab.o"
	@echo "... CharacterTab.i"
	@echo "... CharacterTab.s"
	@echo "... DefaultEditorMode.o"
	@echo "... DefaultEditorMode.i"
	@echo "... DefaultEditorMode.s"
	@echo "... EditorMode.o"
	@echo "... EditorMode.i"
	@echo "... EditorMode.s"
	@echo "... EditorState.o"
	@echo "... EditorState.i"
	@echo "... EditorState.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... EnemyEditorMode.o"
	@echo "... EnemyEditorMode.i"
	@echo "... EnemyEditorMode.s"
	@echo "... EnemySpawnerTile.o"
	@echo "... EnemySpawnerTile.i"
	@echo "... EnemySpawnerTile.s"
	@echo "... EnemySystem.o"
	@echo "... EnemySystem.i"
	@echo "... EnemySystem.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameState.o"
	@echo "... GameState.i"
	@echo "... GameState.s"
	@echo "... GraphicsSettings.o"
	@echo "... GraphicsSettings.i"
	@echo "... GraphicsSettings.s"
	@echo "... Gui.o"
	@echo "... Gui.i"
	@echo "... Gui.s"
	@echo "... HitboxComponent.o"
	@echo "... HitboxComponent.i"
	@echo "... HitboxComponent.s"
	@echo "... Inventory.o"
	@echo "... Inventory.i"
	@echo "... Inventory.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... MainMenuState.o"
	@echo "... MainMenuState.i"
	@echo "... MainMenuState.s"
	@echo "... MeleeWeapon.o"
	@echo "... MeleeWeapon.i"
	@echo "... MeleeWeapon.s"
	@echo "... MovementComponent.o"
	@echo "... MovementComponent.i"
	@echo "... MovementComponent.s"
	@echo "... PauseMenu.o"
	@echo "... PauseMenu.i"
	@echo "... PauseMenu.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... PlayerGUI.o"
	@echo "... PlayerGUI.i"
	@echo "... PlayerGUI.s"
	@echo "... PlayerGUITabs.o"
	@echo "... PlayerGUITabs.i"
	@echo "... PlayerGUITabs.s"
	@echo "... RangedWeapon.o"
	@echo "... RangedWeapon.i"
	@echo "... RangedWeapon.s"
	@echo "... Rat.o"
	@echo "... Rat.i"
	@echo "... Rat.s"
	@echo "... RegularTile.o"
	@echo "... RegularTile.i"
	@echo "... RegularTile.s"
	@echo "... Scorpion.o"
	@echo "... Scorpion.i"
	@echo "... Scorpion.s"
	@echo "... SettingsState.o"
	@echo "... SettingsState.i"
	@echo "... SettingsState.s"
	@echo "... SkillComponent.o"
	@echo "... SkillComponent.i"
	@echo "... SkillComponent.s"
	@echo "... Spider.o"
	@echo "... Spider.i"
	@echo "... Spider.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... Sword.o"
	@echo "... Sword.i"
	@echo "... Sword.s"
	@echo "... Tab.o"
	@echo "... Tab.i"
	@echo "... Tab.s"
	@echo "... TextTagSystem.o"
	@echo "... TextTagSystem.i"
	@echo "... TextTagSystem.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... TileMap.o"
	@echo "... TileMap.i"
	@echo "... TileMap.s"
	@echo "... VectorMath.o"
	@echo "... VectorMath.i"
	@echo "... VectorMath.s"
	@echo "... Weapon.o"
	@echo "... Weapon.i"
	@echo "... Weapon.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stdafx.o"
	@echo "... stdafx.i"
	@echo "... stdafx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

